### PR TITLE
Update StaticText.php

### PR DESCRIPTION
**Pull request by gamadoleo**
remove:
Deprecated: Non-static method JasperPHP\StaticText::formatBox() should not be called statically in

### CODE REVIEW

**Comment by Rctnet** [comment]
i found a problem
https://github.com/QuilhaSoft/JasperPHP/search?q=formatBox
if you move formatbox to a separate class, or to Report, solve easy

**Comment by gamadoleo** [comment]
can't just make the method static can you?

**Comment by Rctnet** [comment]
i use formatText into other objects without instantiate them, if move the formatText to report.php you can modify class:: into statictect, image and texfiled without problems

**Comment by gamadoleo** [comment]
Exactly, notice that the warning is because you are calling a method in static mode but it wasn't declared as static, so what I did was just declare it correctly, I don't understand what that would affect you.

**Comment by gamadoleo** [comment]
I'm not ordering to remove the method, not what I said is that if we declare the method as static it will remove the php warning

**Comment by Rctnet** [comment]
ow, i'm sorry, i see now you just make fix it to static i'm so sorry..

**Pull request merged**
